import code_collection.context_manager_practices
import code_collection.collections_practices
import code_collection.decorators_practices
import code_collection.dictionaries_practices
import code_collection.exceptions_practices
import code_collection.generators_practices
import code_collection.itertools_practices
import code_collection.json_practices
import code_collection.set_practices
import code_collection.shallow_and_deep_copy_practices
import code_collection.logging_practices
import code_collection.threading_practices
import code_collection.string_practices
import code_collection.multiprocessing_practices
import code_collection.list_practices
import code_collection.python_lambda_practices
import code_collection.random_number_practices
import code_collection.tuple_practices










if __name__ == "__main__":
    pass