from context_manager_practices import code as context_manager_code 
from collections_practices import code as collections_code
from decorators_practices import code as decorators_code
from dictionaries_practices import code as dictionaries_code
from exceptions_practices import code as exceptions_code
from generators_practices import code as generators_code
from itertools_practices import code as itertools_code
from json_practices import code as json_code
from set_practices import code as set_code
from shallow_and_deep_copy_practices import code as random_number_code
from logging_practices import code as logging_code
from threading_practices import code as threading_code
from string_practices import code as string_code
from multiprocessing_practices import code as multiprocessing_code
from list_practices import code as list_code
from python_lambda_practices import code as python_lambda_code
from random_number_practices import code as random_number_code
from tuple_practices import code as tuple_code