from . import context_manager_practices 
from . import collections_practices
from . import decorators_practices
from . import dictionaries_practices
from . import exceptions_practices
from . import generators_practices
from . import itertools_practices
from . import json_practices
from . import set_practices
from . import shallow_and_deep_copy_practices
from . import logging_practices
from . import threading_practices
from . import string_practices
from . import multiprocessing_practices
from . import list_practices
from . import python_lambda_practices
from . import random_number_practices
from . import tuple_practices
from . import async_practices